name: CFNN
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip==23.3.1
  - numpy==1.26.4
  - absl-py==1.4.0
  - matplotlib==3.7.1
  - black==24.3.0
  - flake8==7.1.0
  - tensorflow==2.10.0
  - tensorflow-probability==0.14.0
  - munch==2.5.0